# Generated by Django 2.2.1 on 2020-07-21 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WashingMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('washing_machine_number', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField()),
                ('slot_start_time', models.TimeField()),
                ('slot_end_time', models.TimeField()),
                ('slot_status', models.CharField(choices=[('Avilable', 'Avilable'), ('Unavilable', 'Unavilable')], max_length=100)),
                ('washing_machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot_booking.WashingMachine')),
            ],
        ),
    ]
