# Generated by Django 2.2.1 on 2020-07-22 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slot_booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_slot_status', models.CharField(choices=[('Avilable', 'Avilable'), ('Unavilable', 'Unavilable')], max_length=100)),
                ('slot_username', models.CharField(max_length=40)),
                ('user_booked_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot_booking.Slot')),
            ],
        ),
    ]
