# Generated by Django 2.2.1 on 2020-07-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot_booking', '0002_userslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='slot_username',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
